//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoConverter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mp3Record
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<System.DateTime> DownDate { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    }
}
