//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Token {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Token() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoConverter.Resources.Token", typeof(Token).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a simple, Fast and &amp;lt;a href=&apos;http://www.vidfrom.com&apos;&amp;gt;Free Youtube Video Downloader&amp;lt;/a&amp;gt; that allows you to watch your favorite YouTube videos offline on your PC, Mobile, TV or any other device, &amp;lt;a href=&apos;http://www.vidfrom.com&apos;&amp;gt;Convert Youtube to Mp3&amp;lt;/a&amp;gt;, and it also &amp;lt;a href=&apos;http://www.vidfrom.com&apos;&amp;gt;Soundcloud Downloader&amp;lt;/a&amp;gt;, &amp;lt;a href=&apos;http://www.vidfrom.com&apos;&amp;gt; Facebook Video Downloader&amp;lt;/a&amp;gt;, &amp;lt;a href=&apos;http://www.vidfrom.com&apos;&amp;gt;Instagram Video Downloader&amp;lt;/a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Mp3.
        /// </summary>
        public static string DownloadMp3 {
            get {
                return ResourceManager.GetString("DownloadMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Video.
        /// </summary>
        public static string DownloadVideo {
            get {
                return ResourceManager.GetString("DownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;a href=&apos;http://www.vidfrom.com&apos;&amp;gt;Youtube Video Downloader&amp;lt;/a&amp;gt;, YouTube to MP3, Facebook Video Downloader, Soundcloud Downloader, Instagram Video Downloader...
        /// </summary>
        public static string FirstSentence {
            get {
                return ResourceManager.GetString("FirstSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Download Facebook Videos and save them to computer or mobile or any device.
        /// </summary>
        public static string HowToDownFaceDesc {
            get {
                return ResourceManager.GetString("HowToDownFaceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Download Facebook Videos.
        /// </summary>
        public static string HowToDownFaceTilte {
            get {
                return ResourceManager.GetString("HowToDownFaceTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to download and convert a video :.
        /// </summary>
        public static string HowToDownload {
            get {
                return ResourceManager.GetString("HowToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Video Downloader, Youtube to Mp3, Soundcloud Downloader, Facebook Video Downloader,Instagram Video Downloader,Twitter Video Downloader.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You like this service? Like it on Facebook!.
        /// </summary>
        public static string LikeService {
            get {
                return ResourceManager.GetString("LikeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VidFrom is a simple, Fast and Free Youtube Video Downloader that allows you to Convert Youtube to Mp3, and its also Soundcloud Downloader &amp; Facebook Video Downloader &amp; Instagram Video Downloader &amp; Twitter Video Downloader. Also supports Vimeo, vine.co and many other online video sites..
        /// </summary>
        public static string PDescribtion {
            get {
                return ResourceManager.GetString("PDescribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter video link. example.
        /// </summary>
        public static string PlaceHolder {
            get {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Quality.
        /// </summary>
        public static string SelectFormat {
            get {
                return ResourceManager.GetString("SelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your Video Link at &apos;Video Link&apos; and press Download..
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Download format..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the &apos;Download&apos; button at the bottom to start the Download..
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported sites.
        /// </summary>
        public static string SupportedSites {
            get {
                return ResourceManager.GetString("SupportedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Youtube Video Downloader &amp; Youtube to Mp3 &amp; Soundcloud Downloader &amp; Facebook &amp; Instagram &amp; Twitter &amp; Vimeo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
